// @flow

import { FEATURE_NAME } from "./consts/index";

export const SYNC_MY_AUDIO = `${FEATURE_NAME}/SYNC_MY_AUDIO`;

export const FETCH_ALL_MY_AUDIO_SUCCESS = `${FEATURE_NAME}/FETCH_ALL_MY_AUDIO_SUCCESS`;

export const INITIAL_FETCH_MY_AUDIO_SUCCESS = `${FEATURE_NAME}/INITIAL_FETCH_MY_AUDIO_SUCCESS`;
