// @flow

import { FEATURE_NAME } from "./consts/index";

export const CONNECTION_CHANGE = `${FEATURE_NAME}/CONNECTION_CHANGE`;
export const CONNECTION_OFFLINE = `${FEATURE_NAME}/CONNECTION_OFFLINE`;
export const CONNECTION_ONLINE = `${FEATURE_NAME}/CONNECTION_ONLINE`;
export const CONNECTION_UNKNOWN = `${FEATURE_NAME}/CONNECTION_UNKNOWN`;
